FROM python:3.8-buster

COPY . /app
WORKDIR /app

RUN pip install poetry
RUN poetry export --dev --format requirements.txt --output requirements.txt \
  && pip install -r requirements.txt

CMD ["pytest"]
